# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 260)
        MainWindow.setWindowOpacity(0.0)
        self.WMain = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WMain.sizePolicy().hasHeightForWidth())
        self.WMain.setSizePolicy(sizePolicy)
        self.WMain.setObjectName("WMain")
        self.widget = QtWidgets.QWidget(self.WMain)
        self.widget.setGeometry(QtCore.QRect(10, 10, 461, 201))
        self.widget.setObjectName("widget")
        self.GLMain = QtWidgets.QGridLayout(self.widget)
        self.GLMain.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.GLMain.setContentsMargins(0, 0, 0, 0)
        self.GLMain.setObjectName("GLMain")
        self.GLRCol = QtWidgets.QGridLayout()
        self.GLRCol.setObjectName("GLRCol")
        self.GBMetr = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GBMetr.sizePolicy().hasHeightForWidth())
        self.GBMetr.setSizePolicy(sizePolicy)
        self.GBMetr.setObjectName("GBMetr")
        self.widget1 = QtWidgets.QWidget(self.GBMetr)
        self.widget1.setGeometry(QtCore.QRect(0, 20, 221, 111))
        self.widget1.setObjectName("widget1")
        self.GLMetr = QtWidgets.QGridLayout(self.widget1)
        self.GLMetr.setContentsMargins(0, 0, 0, 0)
        self.GLMetr.setObjectName("GLMetr")
        self.LHomogen = QtWidgets.QLabel(self.widget1)
        self.LHomogen.setObjectName("LHomogen")
        self.GLMetr.addWidget(self.LHomogen, 0, 0, 1, 1)
        self.LHomogenVal = QtWidgets.QLabel(self.widget1)
        self.LHomogenVal.setObjectName("LHomogenVal")
        self.GLMetr.addWidget(self.LHomogenVal, 0, 1, 1, 1)
        self.LCompleteness = QtWidgets.QLabel(self.widget1)
        self.LCompleteness.setObjectName("LCompleteness")
        self.GLMetr.addWidget(self.LCompleteness, 1, 0, 1, 1)
        self.LCompletenessVal = QtWidgets.QLabel(self.widget1)
        self.LCompletenessVal.setObjectName("LCompletenessVal")
        self.GLMetr.addWidget(self.LCompletenessVal, 1, 1, 1, 1)
        self.LVMeas = QtWidgets.QLabel(self.widget1)
        self.LVMeas.setObjectName("LVMeas")
        self.GLMetr.addWidget(self.LVMeas, 2, 0, 1, 1)
        self.LVMeasVal = QtWidgets.QLabel(self.widget1)
        self.LVMeasVal.setObjectName("LVMeasVal")
        self.GLMetr.addWidget(self.LVMeasVal, 2, 1, 1, 1)
        self.LWTime = QtWidgets.QLabel(self.widget1)
        self.LWTime.setObjectName("LWTime")
        self.GLMetr.addWidget(self.LWTime, 3, 0, 1, 1)
        self.LWTimeVal = QtWidgets.QLabel(self.widget1)
        self.LWTimeVal.setObjectName("LWTimeVal")
        self.GLMetr.addWidget(self.LWTimeVal, 3, 1, 1, 1)
        self.GLRCol.addWidget(self.GBMetr, 0, 0, 1, 1)
        self.BGetPlots = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BGetPlots.sizePolicy().hasHeightForWidth())
        self.BGetPlots.setSizePolicy(sizePolicy)
        self.BGetPlots.setObjectName("BGetPlots")
        self.GLRCol.addWidget(self.BGetPlots, 1, 0, 1, 1)
        self.BClust = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BClust.sizePolicy().hasHeightForWidth())
        self.BClust.setSizePolicy(sizePolicy)
        self.BClust.setObjectName("BClust")
        self.GLRCol.addWidget(self.BClust, 2, 0, 1, 1)
        self.GLMain.addLayout(self.GLRCol, 0, 1, 3, 1)
        self.GBInputData = QtWidgets.QGroupBox(self.widget)
        self.GBInputData.setObjectName("GBInputData")
        self.formLayout = QtWidgets.QFormLayout(self.GBInputData)
        self.formLayout.setObjectName("formLayout")
        self.LLang = QtWidgets.QLabel(self.GBInputData)
        self.LLang.setObjectName("LLang")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LLang)
        self.CBLangVal = QtWidgets.QComboBox(self.GBInputData)
        self.CBLangVal.setObjectName("CBLangVal")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CBLangVal)
        self.LCorp = QtWidgets.QLabel(self.GBInputData)
        self.LCorp.setObjectName("LCorp")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.LCorp)
        self.CBCorpVal = QtWidgets.QComboBox(self.GBInputData)
        self.CBCorpVal.setObjectName("CBCorpVal")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.CBCorpVal)
        self.GLMain.addWidget(self.GBInputData, 0, 0, 1, 1)
        self.GLOntoSet = QtWidgets.QGridLayout()
        self.GLOntoSet.setObjectName("GLOntoSet")
        self.BOpenSet = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BOpenSet.sizePolicy().hasHeightForWidth())
        self.BOpenSet.setSizePolicy(sizePolicy)
        self.BOpenSet.setObjectName("BOpenSet")
        self.GLOntoSet.addWidget(self.BOpenSet, 0, 0, 1, 1)
        self.BEditSet = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BEditSet.sizePolicy().hasHeightForWidth())
        self.BEditSet.setSizePolicy(sizePolicy)
        self.BEditSet.setObjectName("BEditSet")
        self.GLOntoSet.addWidget(self.BEditSet, 1, 0, 1, 1)
        self.BViewOnto = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BViewOnto.sizePolicy().hasHeightForWidth())
        self.BViewOnto.setSizePolicy(sizePolicy)
        self.BViewOnto.setObjectName("BViewOnto")
        self.GLOntoSet.addWidget(self.BViewOnto, 2, 0, 1, 1)
        self.GLMain.addLayout(self.GLOntoSet, 1, 0, 2, 1)
        MainWindow.setCentralWidget(self.WMain)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 477, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GBMetr.setTitle(_translate("MainWindow", "Метрики"))
        self.LHomogen.setText(_translate("MainWindow", "Однородность:"))
        self.LHomogenVal.setText(_translate("MainWindow", "TextLabel"))
        self.LCompleteness.setText(_translate("MainWindow", "Полнота:"))
        self.LCompletenessVal.setText(_translate("MainWindow", "TextLabel"))
        self.LVMeas.setText(_translate("MainWindow", "V-мера:"))
        self.LVMeasVal.setText(_translate("MainWindow", "TextLabel"))
        self.LWTime.setText(_translate("MainWindow", "Время кластеризации:"))
        self.LWTimeVal.setText(_translate("MainWindow", "TextLabel"))
        self.BGetPlots.setText(_translate("MainWindow", "Получить графики"))
        self.BClust.setText(_translate("MainWindow", "Кластеризация"))
        self.GBInputData.setTitle(_translate("MainWindow", "Входные данные"))
        self.LLang.setText(_translate("MainWindow", "Язык:"))
        self.LCorp.setText(_translate("MainWindow", "Корпус:"))
        self.BOpenSet.setText(_translate("MainWindow", "Открыть настройки"))
        self.BEditSet.setText(_translate("MainWindow", "Изменить настройки"))
        self.BViewOnto.setText(_translate("MainWindow", "Просмотр онтологии"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

